[pytest]
pythonpath = .
asyncio_mode = auto
markers = 
    e2e: marks tests as end-to-end tests
filterwarnings =
    ignore:pkg_resources is deprecated:UserWarning
    ignore:Deprecated call to .pkg_resources.declare_namespace:DeprecationWarning
    ignore:Call to .__init__. function with deprecated usage of input argument/s .retry_on_timeout.:DeprecationWarning
    ignore:Support for class-based .config. is deprecated:pydantic.PydanticDeprecatedSince20
    ignore:The .google-generativeai. package is deprecated:DeprecationWarning
    ignore:All support for the .google.generativeai. package has ended:FutureWarning
    ignore:Trying to unpickle estimator .* from version:sklearn.exceptions.InconsistentVersionWarning