"""initial_schema

Revision ID: f5d8ac71f614
Revises: 
Create Date: 2026-06-04 20:02:53.221839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d8ac71f614'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarity'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('hub_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_feedback_id'), 'hub_feedback', ['id'], unique=False)
    op.create_table('hub_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_news_id'), 'hub_news', ['id'], unique=False)
    op.create_table('hub_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.String(length=50), nullable=True),
    sa.Column('period_end', sa.String(length=50), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('strategy_json', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delete_token', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hub_verified_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_verified_strategies_id'), 'hub_verified_strategies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('affiliate_commission_rate', sa.Float(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('push_subscription', sa.JSON(), nullable=True),
    sa.Column('symbol_selection_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('tradingview_webhook_token', sa.String(), nullable=True),
    sa.Column('referred_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_tradingview_webhook_token'), 'users', ['tradingview_webhook_token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('image_mime_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_user_id'), 'ai_chat_messages', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.String(), nullable=False),
    sa.Column('encrypted_api_secret', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key_hash'), 'api_keys', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_management', sa.JSON(), nullable=False),
    sa.Column('backtest_risk_management', sa.JSON(), nullable=True),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('exchange_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_app_configs_id'), 'app_configs', ['id'], unique=False)
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_feature_name'), 'bonuses', ['feature_name'], unique=False)
    op.create_index(op.f('ix_bonuses_id'), 'bonuses', ['id'], unique=False)
    op.create_index(op.f('ix_bonuses_status'), 'bonuses', ['status'], unique=False)
    op.create_index(op.f('ix_bonuses_user_id'), 'bonuses', ['user_id'], unique=False)
    op.create_table('dataset_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('feature_list', sa.JSON(), nullable=True),
    sa.Column('dataset_shape', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_runs_celery_task_id'), 'dataset_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_dataset_runs_name'), 'dataset_runs', ['name'], unique=False)
    op.create_index(op.f('ix_dataset_runs_status'), 'dataset_runs', ['status'], unique=False)
    op.create_index(op.f('ix_dataset_runs_user_id'), 'dataset_runs', ['user_id'], unique=False)
    op.create_table('genes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('rarity', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('first_discovered_by', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['first_discovered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_id'), 'genes', ['id'], unique=False)
    op.create_table('genetic_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genetic_runs_celery_task_id'), 'genetic_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_genetic_runs_status'), 'genetic_runs', ['status'], unique=False)
    op.create_index(op.f('ix_genetic_runs_user_id'), 'genetic_runs', ['user_id'], unique=False)
    op.create_table('hub_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['hub_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_comments_id'), 'hub_comments', ['id'], unique=False)
    op.create_table('paper_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset', name='_user_asset_uc')
    )
    op.create_index(op.f('ix_paper_wallets_id'), 'paper_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_paper_wallets_user_id'), 'paper_wallets', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nowpayments_payment_id', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_nowpayments_payment_id'), 'payments', ['nowpayments_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('symbol_selection_mode', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('use_ml_confirmation', sa.Boolean(), nullable=False),
    sa.Column('foundation_weights', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('oracle_regime', sa.Integer(), nullable=True),
    sa.Column('oracle_confidence', sa.Float(), nullable=True),
    sa.Column('parent_strategy_id', sa.String(), nullable=True),
    sa.Column('generation', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source_mutation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_strategy_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_configs_name'), 'strategy_configs', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_configs_parent_strategy_id'), 'strategy_configs', ['parent_strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_configs_user_id'), 'strategy_configs', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('screenshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('symbol_strategy_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('total_pnl_usd', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('trade_results_buffer_json', sa.JSON(), nullable=False),
    sa.Column('current_risk_multiplier_index', sa.Integer(), nullable=False),
    sa.Column('last_penalty_timestamp', sa.Float(), nullable=False),
    sa.Column('total_trades_for_assessment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'strategy_name', name='_user_symbol_strategy_uc')
    )
    op.create_index(op.f('ix_symbol_strategy_performance_id'), 'symbol_strategy_performance', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_strategy_performance_strategy_name'), 'symbol_strategy_performance', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_symbol_strategy_performance_symbol'), 'symbol_strategy_performance', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbol_strategy_performance_user_id'), 'symbol_strategy_performance', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='_user_achievement_uc')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kpi_results_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('equity_curve_json', sa.JSON(), nullable=True),
    sa.Column('analytics_report_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_name'), 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_index(op.f('ix_backtest_runs_task_id'), 'backtest_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_user_id'), 'backtest_runs', ['user_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('affiliate_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('source_payment_id', sa.String(), nullable=False),
    sa.Column('commission_amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('becomes_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_affiliate_user_id'), 'commissions', ['affiliate_user_id'], unique=False)
    op.create_index(op.f('ix_commissions_referred_user_id'), 'commissions', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_commissions_source_payment_id'), 'commissions', ['source_payment_id'], unique=False)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.create_table('found_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('kpis_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['genetic_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_strategies_run_id'), 'found_strategies', ['run_id'], unique=False)
    op.create_table('phantom_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_trade_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strategy_config_id', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_stop_loss', sa.Float(), nullable=False),
    sa.Column('initial_take_profit', sa.Float(), nullable=False),
    sa.Column('be_trigger_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('be_exit_price', sa.Float(), nullable=False),
    sa.Column('real_pnl_pct', sa.Float(), nullable=False),
    sa.Column('real_pnl_usd', sa.Float(), nullable=True),
    sa.Column('phantom_status', sa.String(), nullable=False),
    sa.Column('phantom_exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phantom_exit_price', sa.Float(), nullable=True),
    sa.Column('phantom_pnl_pct', sa.Float(), nullable=True),
    sa.Column('phantom_pnl_usd', sa.Float(), nullable=True),
    sa.Column('mfe_after_be', sa.Float(), nullable=True),
    sa.Column('mae_after_be', sa.Float(), nullable=True),
    sa.Column('mfe_price', sa.Float(), nullable=True),
    sa.Column('mae_price', sa.Float(), nullable=True),
    sa.Column('candles_to_resolution', sa.Integer(), nullable=True),
    sa.Column('timeout_candles', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phantom_trades_id'), 'phantom_trades', ['id'], unique=False)
    op.create_index(op.f('ix_phantom_trades_phantom_status'), 'phantom_trades', ['phantom_status'], unique=False)
    op.create_index(op.f('ix_phantom_trades_real_trade_id'), 'phantom_trades', ['real_trade_id'], unique=False)
    op.create_index(op.f('ix_phantom_trades_symbol'), 'phantom_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_phantom_trades_user_id'), 'phantom_trades', ['user_id'], unique=False)
    op.create_table('support_ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_messages_id'), 'support_ticket_messages', ['id'], unique=False)
    op.create_index(op.f('ix_support_ticket_messages_ticket_id'), 'support_ticket_messages', ['ticket_id'], unique=False)
    op.create_table('trade_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_trade_id', sa.String(), nullable=True),
    sa.Column('strategy_config_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('timestamp_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('win_rate_contribution', sa.Integer(), nullable=True),
    sa.Column('profit_factor_gross_profit', sa.Float(), nullable=True),
    sa.Column('profit_factor_gross_loss', sa.Float(), nullable=True),
    sa.Column('used_foundations', sa.JSON(), nullable=True),
    sa.Column('used_filters', sa.JSON(), nullable=True),
    sa.Column('used_indicators', sa.JSON(), nullable=True),
    sa.Column('used_management_blocks', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_analytics_id'), 'trade_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_trade_analytics_symbol'), 'trade_analytics', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_analytics_timestamp_close'), 'trade_analytics', ['timestamp_close'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_uuid', sa.String(), nullable=False),
    sa.Column('timestamp_close', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('strategy_config_id', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('trade_mode', sa.String(length=10), server_default='LIVE', nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('position_entry_id', sa.String(), nullable=True),
    sa.Column('exit_type', sa.String(), nullable=True),
    sa.Column('is_final_exit', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('signal_details_json', sa.JSON(), nullable=True),
    sa.Column('timestamp_signal', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_entry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_floating_profit', sa.Float(), nullable=True),
    sa.Column('max_floating_loss', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_api_key_id'), 'trades', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_position_entry_id'), 'trades', ['position_entry_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_config_id'), 'trades', ['strategy_config_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_timestamp_close'), 'trades', ['timestamp_close'], unique=False)
    op.create_index(op.f('ix_trades_trade_mode'), 'trades', ['trade_mode'], unique=False)
    op.create_index(op.f('ix_trades_trade_uuid'), 'trades', ['trade_uuid'], unique=True)
    op.create_table('training_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_celery_task_id'), 'training_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_training_runs_dataset_id'), 'training_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_training_runs_status'), 'training_runs', ['status'], unique=False)
    op.create_index(op.f('ix_training_runs_user_id'), 'training_runs', ['user_id'], unique=False)
    op.create_table('user_genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_strategy_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['source_strategy_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gene_id', name='_user_gene_uc')
    )
    op.create_index(op.f('ix_user_genes_gene_id'), 'user_genes', ['gene_id'], unique=False)
    op.create_index(op.f('ix_user_genes_id'), 'user_genes', ['id'], unique=False)
    op.create_index(op.f('ix_user_genes_user_id'), 'user_genes', ['user_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.String(), nullable=False),
    sa.Column('client_order_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('timestamp_entry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_exit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('decision_trace_json', sa.JSON(), nullable=True),
    sa.Column('l2_ideal_entry_price', sa.Float(), nullable=True),
    sa.Column('l2_entry_slippage_usd', sa.Float(), nullable=True),
    sa.Column('l2_entry_filled_quantity', sa.Float(), nullable=True),
    sa.Column('l2_ideal_exit_price', sa.Float(), nullable=True),
    sa.Column('l2_exit_slippage_usd', sa.Float(), nullable=True),
    sa.Column('l2_filled_qty_at_exit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_client_order_id'), 'backtest_trades', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_timestamp_entry'), 'backtest_trades', ['timestamp_entry'], unique=False)
    op.create_table('shared_backtests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('backtest_run_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_slug', sa.String(), nullable=False),
    sa.Column('is_strategy_name_public', sa.Boolean(), nullable=False),
    sa.Column('are_parameters_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_backtests_backtest_run_id'), 'shared_backtests', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_shared_backtests_public_slug'), 'shared_backtests', ['public_slug'], unique=True)
    op.create_index(op.f('ix_shared_backtests_user_id'), 'shared_backtests', ['user_id'], unique=False)
    op.create_table('backtest_trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['backtest_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trade_executions_id'), 'backtest_trade_executions', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trade_executions_timestamp'), 'backtest_trade_executions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_trade_executions_trade_id'), 'backtest_trade_executions', ['trade_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.String(), nullable=False),
    sa.Column('shared_backtest_slug', sa.String(), nullable=False),
    sa.Column('period', sa.Enum('WEEKLY', 'MONTHLY', 'ALL_TIME', name='leaderboardperiod'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['shared_backtest_slug'], ['shared_backtests.public_slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_backtest_trade_executions_trade_id'), table_name='backtest_trade_executions')
    op.drop_index(op.f('ix_backtest_trade_executions_timestamp'), table_name='backtest_trade_executions')
    op.drop_index(op.f('ix_backtest_trade_executions_id'), table_name='backtest_trade_executions')
    op.drop_table('backtest_trade_executions')
    op.drop_index(op.f('ix_shared_backtests_user_id'), table_name='shared_backtests')
    op.drop_index(op.f('ix_shared_backtests_public_slug'), table_name='shared_backtests')
    op.drop_index(op.f('ix_shared_backtests_backtest_run_id'), table_name='shared_backtests')
    op.drop_table('shared_backtests')
    op.drop_index(op.f('ix_backtest_trades_timestamp_entry'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_client_order_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_user_genes_user_id'), table_name='user_genes')
    op.drop_index(op.f('ix_user_genes_id'), table_name='user_genes')
    op.drop_index(op.f('ix_user_genes_gene_id'), table_name='user_genes')
    op.drop_table('user_genes')
    op.drop_index(op.f('ix_training_runs_user_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_status'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_dataset_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_celery_task_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_trades_trade_uuid'), table_name='trades')
    op.drop_index(op.f('ix_trades_trade_mode'), table_name='trades')
    op.drop_index(op.f('ix_trades_timestamp_close'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_config_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_position_entry_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_api_key_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trade_analytics_timestamp_close'), table_name='trade_analytics')
    op.drop_index(op.f('ix_trade_analytics_symbol'), table_name='trade_analytics')
    op.drop_index(op.f('ix_trade_analytics_id'), table_name='trade_analytics')
    op.drop_table('trade_analytics')
    op.drop_index(op.f('ix_support_ticket_messages_ticket_id'), table_name='support_ticket_messages')
    op.drop_index(op.f('ix_support_ticket_messages_id'), table_name='support_ticket_messages')
    op.drop_table('support_ticket_messages')
    op.drop_index(op.f('ix_phantom_trades_user_id'), table_name='phantom_trades')
    op.drop_index(op.f('ix_phantom_trades_symbol'), table_name='phantom_trades')
    op.drop_index(op.f('ix_phantom_trades_real_trade_id'), table_name='phantom_trades')
    op.drop_index(op.f('ix_phantom_trades_phantom_status'), table_name='phantom_trades')
    op.drop_index(op.f('ix_phantom_trades_id'), table_name='phantom_trades')
    op.drop_table('phantom_trades')
    op.drop_index(op.f('ix_found_strategies_run_id'), table_name='found_strategies')
    op.drop_table('found_strategies')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_source_payment_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_referred_user_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_affiliate_user_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_backtest_runs_user_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_task_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_name'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_symbol_strategy_performance_user_id'), table_name='symbol_strategy_performance')
    op.drop_index(op.f('ix_symbol_strategy_performance_symbol'), table_name='symbol_strategy_performance')
    op.drop_index(op.f('ix_symbol_strategy_performance_strategy_name'), table_name='symbol_strategy_performance')
    op.drop_index(op.f('ix_symbol_strategy_performance_id'), table_name='symbol_strategy_performance')
    op.drop_table('symbol_strategy_performance')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_strategy_configs_user_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_parent_strategy_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_name'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_nowpayments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_paper_wallets_user_id'), table_name='paper_wallets')
    op.drop_index(op.f('ix_paper_wallets_id'), table_name='paper_wallets')
    op.drop_table('paper_wallets')
    op.drop_index(op.f('ix_hub_comments_id'), table_name='hub_comments')
    op.drop_table('hub_comments')
    op.drop_index(op.f('ix_genetic_runs_user_id'), table_name='genetic_runs')
    op.drop_index(op.f('ix_genetic_runs_status'), table_name='genetic_runs')
    op.drop_index(op.f('ix_genetic_runs_celery_task_id'), table_name='genetic_runs')
    op.drop_table('genetic_runs')
    op.drop_index(op.f('ix_genes_id'), table_name='genes')
    op.drop_table('genes')
    op.drop_index(op.f('ix_dataset_runs_user_id'), table_name='dataset_runs')
    op.drop_index(op.f('ix_dataset_runs_status'), table_name='dataset_runs')
    op.drop_index(op.f('ix_dataset_runs_name'), table_name='dataset_runs')
    op.drop_index(op.f('ix_dataset_runs_celery_task_id'), table_name='dataset_runs')
    op.drop_table('dataset_runs')
    op.drop_index(op.f('ix_bonuses_user_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_status'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_feature_name'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_app_configs_id'), table_name='app_configs')
    op.drop_table('app_configs')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_chat_messages_user_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tradingview_webhook_token'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hub_verified_strategies_id'), table_name='hub_verified_strategies')
    op.drop_table('hub_verified_strategies')
    op.drop_table('hub_topics')
    op.drop_index(op.f('ix_hub_news_id'), table_name='hub_news')
    op.drop_table('hub_news')
    op.drop_index(op.f('ix_hub_feedback_id'), table_name='hub_feedback')
    op.drop_table('hub_feedback')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
