export interface KBArticle {
	id: string;
	title: string;
	description: string;
	category: "getting-started" | "features" | "billing" | "advanced";
	tags: string[];
}

export const kbArticles: Record<"ru" | "en", KBArticle[]> = {
	ru: [
		{
			id: "api-setup",
			title: "Настройка API ключей",
			description: "Как правильно подключить вашу биржу к DepthSight",
			category: "getting-started",
			tags: ["binance", "bybit", "api", "security"],
		},
		{
			id: "engine-guide",
			title: "Движок платформы",
			description: "Как работает ядро системы в реальном времени",
			category: "features",
			tags: ["engine", "trading", "execution"],
		},
		{
			id: "backtest-guide",
			title: "Система бэктестов",
			description: "Различия между Fast Vector и событийным бэктестером",
			category: "features",
			tags: ["backtest", "analytics", "statistics"],
		},
		{
			id: "strategy-editor",
			title: "Редактор стратегий",
			description: "Принципы иерархического конструктора стратегий",
			category: "features",
			tags: ["strategy", "editor", "visual builder"],
		},
		{
			id: "blocks-filters",
			title: "Секция: Фильтры",
			description: "Как ограничить работу бота в неподходящих условиях",
			category: "features",
			tags: ["filters", "time", "trend", "volatility"],
		},
		{
			id: "blocks-foundations",
			title: "Секция: Основания",
			description: "Механика рынка: плотности, лента и психология",
			category: "features",
			tags: ["foundations", "orderbook", "tape", "L2"],
		},
		{
			id: "blocks-indicators",
			title: "Секция: Индикаторы",
			description: "Математика трейдинга и свечные паттерны",
			category: "features",
			tags: ["indicators", "rsi", "ma", "patterns"],
		},
		{
			id: "blocks-logic",
			title: "Секция: Логика",
			description: "Как объединять блоки в сложные стратегии",
			category: "features",
			tags: ["logic", "and", "or", "multi-tf"],
		},
		{
			id: "blocks-management",
			title: "Секция: Управление",
			description: "Дисциплина выходов: стопы, тейки и трейлинг",
			category: "features",
			tags: ["management", "sl", "tp", "trailing", "dca"],
		},
		{
			id: "troubleshooting-guide",
			title: "Диагностика и частые ошибки",
			description: "Что делать, если бот не открывает сделки",
			category: "features",
			tags: ["troubleshooting", "diagnostics", "errors", "help"],
		},
		{
			id: "billing-guide",
			title: "Тарифы и оплата",
			description: "Описание планов и способов активации доступа",
			category: "billing",
			tags: ["billing", "plans", "crypto", "bitcart"],
		},
		{
			id: "ai-copilot",
			title: "AI Copilot",
			description: "Создание стратегий с помощью искусственного интеллекта",
			category: "advanced",
			tags: ["ai", "copilot", "llm", "automation"],
		},
		{
			id: "oracle-regime",
			title: "ИИ Оракул (Oracle Regime)",
			description: "Как нейросеть определяет фазы рынка и волатильность",
			category: "advanced",
			tags: ["ai", "oracle", "machine learning", "regime"],
		},
		{
			id: "tradingview-integration",
			title: "Интеграция с TradingView",
			description: "Симбиоз внешних индикаторов и фильтров DepthSight",
			category: "advanced",
			tags: ["tradingview", "webhook", "pine script", "signals"],
		},
		{
			id: "portfolio-management",
			title: "Портфельное управление",
			description: "Как запускать несколько стратегий и диверсифицировать риски",
			category: "advanced",
			tags: ["portfolio", "diversification", "risk", "management"],
		},
		{
			id: "genetic-optimization",
			title: "Генетическая оптимизация",
			description: "Автоматический поиск лучших параметров стратегии",
			category: "advanced",
			tags: ["genetic", "optimization", "ai", "parameters"],
		},
		{
			id: "dynamic-selection",
			title: "Динамический выбор монет",
			description: "Автоматический поиск активных пар на рынке",
			category: "advanced",
			tags: ["dynamic", "selection", "volume", "volatility"],
		},
		{
			id: "weighted-foundations",
			title: "Взвешенные основания",
			description: "Продвинутая система оценки качества сигналов",
			category: "advanced",
			tags: ["foundations", "weights", "scoring", "filters"],
		},
		{
			id: "dynamic-links",
			title: "Динамические ссылки",
			description: "Как настроить взаимодействие между блоками стратегии",
			category: "advanced",
			tags: ["links", "logic", "automation", "dynamic"],
		},
		{
			id: "risk-management",
			title: "Риск-менеджмент",
			description: "Настройка стоп-лоссов и лимитов просадки",
			category: "advanced",
			tags: ["risk", "money management", "stop-loss"],
		},
	],
	en: [
		{
			id: "api-setup",
			title: "API Keys Setup",
			description: "How to correctly connect your exchange to DepthSight",
			category: "getting-started",
			tags: ["binance", "bybit", "api", "security"],
		},
		{
			id: "engine-guide",
			title: "Platform Engine",
			description: "How the system core works in real-time",
			category: "features",
			tags: ["engine", "trading", "execution"],
		},
		{
			id: "backtest-guide",
			title: "Backtesting System",
			description: "Difference between Fast Vector and Event-driven testers",
			category: "features",
			tags: ["backtest", "analytics", "statistics"],
		},
		{
			id: "strategy-editor",
			title: "Strategy Editor",
			description: "Principles of the hierarchical strategy builder",
			category: "features",
			tags: ["strategy", "editor", "visual builder"],
		},
		{
			id: "community-hub",
			title: "Discovery Hub",
			description: "Verified templates, trading ideas, and community",
			category: "features",
			tags: ["community", "hub", "templates", "ideas"],
		},
		{
			id: "blocks-filters",
			title: "Section: Filters",
			description: "How to restrict the bot in unsuitable conditions",
			category: "features",
			tags: ["filters", "time", "trend", "volatility"],
		},
		{
			id: "blocks-foundations",
			title: "Section: Foundations",
			description: "Market mechanics: order book, tape, and psychology",
			category: "features",
			tags: ["foundations", "orderbook", "tape", "L2"],
		},
		{
			id: "blocks-indicators",
			title: "Section: Indicators",
			description: "Trading math and candlestick patterns",
			category: "features",
			tags: ["indicators", "rsi", "ma", "patterns"],
		},
		{
			id: "blocks-logic",
			title: "Section: Logic",
			description: "How to combine blocks into complex strategies",
			category: "features",
			tags: ["logic", "and", "or", "multi-tf"],
		},
		{
			id: "blocks-management",
			title: "Section: Management",
			description: "Exit discipline: stops, takes, and trailing",
			category: "features",
			tags: ["management", "sl", "tp", "trailing", "dca"],
		},
		{
			id: "analytics-guide",
			title: "Analytics and Statistics",
			description: "How to read PnL charts, heatmaps, and metrics",
			category: "features",
			tags: ["analytics", "statistics", "heatmap", "pnl"],
		},
		{
			id: "troubleshooting-guide",
			title: "Troubleshooting Guide",
			description: "What to do if the bot is not opening trades",
			category: "features",
			tags: ["troubleshooting", "diagnostics", "errors", "help"],
		},
		{
			id: "billing-guide",
			title: "Plans and Billing",
			description: "Description of plans and payment methods",
			category: "billing",
			tags: ["billing", "plans", "crypto", "bitcart"],
		},
		{
			id: "ai-copilot",
			title: "AI Copilot",
			description: "Creating strategies using artificial intelligence",
			category: "advanced",
			tags: ["ai", "copilot", "llm", "automation"],
		},
		{
			id: "oracle-regime",
			title: "AI Oracle Regime",
			description: "How the neural network detects market phases and volatility",
			category: "advanced",
			tags: ["ai", "oracle", "machine learning", "regime"],
		},
		{
			id: "tradingview-integration",
			title: "TradingView Integration",
			description: "Symbiosis of external indicators and DepthSight filters",
			category: "advanced",
			tags: ["tradingview", "webhook", "pine script", "signals"],
		},
		{
			id: "portfolio-management",
			title: "Portfolio Management",
			description: "How to run multiple strategies and diversify risks",
			category: "advanced",
			tags: ["portfolio", "diversification", "risk", "management"],
		},
		{
			id: "genetic-optimization",
			title: "Genetic Optimization",
			description: "Automated search for the best strategy parameters",
			category: "advanced",
			tags: ["genetic", "optimization", "ai", "parameters"],
		},
		{
			id: "dynamic-selection",
			title: "Dynamic Coin Selection",
			description: "Automatically finding active pairs on the market",
			category: "advanced",
			tags: ["dynamic", "selection", "volume", "volatility"],
		},
		{
			id: "weighted-foundations",
			title: "Weighted Foundations",
			description: "Advanced signal quality assessment system",
			category: "advanced",
			tags: ["foundations", "weights", "scoring", "filters"],
		},
		{
			id: "dynamic-links",
			title: "Dynamic Links",
			description: "Configuring communication between strategy blocks",
			category: "advanced",
			tags: ["links", "logic", "automation", "dynamic"],
		},
		{
			id: "grid-dca-guide",
			title: "Grid & DCA Strategies",
			description: "Smart grids, DCA calculator, and block integration",
			category: "advanced",
			tags: ["grid", "dca", "martingale", "calculator"],
		},
		{
			id: "risk-management",
			title: "Risk Management",
			description: "Configuring stop-losses and drawdown limits",
			category: "advanced",
			tags: ["risk", "money management", "stop-loss"],
		},
	],
};

